server:
  port: 80
  tomcat:
    max-swallow-size: 50MB

spring:
  application:
    name: bur-crm
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: database/changelog-master.xml
    enabled: true
  datasource:
    jdbc-url: jdbc:postgresql://localhost:${POSTGRES_PORT_WRITE}/${POSTGRES_DB_WRITE}?escapeSyntaxCallMode=callIfNoReturn
    username: ${POSTGRES_USER_WRITE}
    password: ${POSTGRES_PASSWORD_WRITE}
    driver-class-name: org.postgresql.Driver
    auto-commit: false
  data:
    jpa:
      repositories:
        enabled: false
    jdbc:
      repositories:
        enabled: false

rsa:
  private-key: classpath:/certs/private.pem
  public-key: classpath:/certs/public.pem

bur:
  username: ${BUR_USERNAME}
  key: ${BUR_KEY}