server:
  port: 0

spring:
  application:
    name: bur-crm
  profiles:
    active: local
  threads:
    virtual:
      enabled: true
  liquibase:
    change-log: database/changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    jdbc-url: jdbc:postgresql://localhost:${POSTGRES_PORT_WRITE}/${POSTGRES_DB_WRITE}
    username: ${POSTGRES_USER_WRITE}
    password: ${POSTGRES_PASSWORD_WRITE}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: burcrm@gmail.com
    password: ${JAVA_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true