services:

  crm-postgres-write:
    container_name: 'crm-postgres-write'
    image: postgres:16
    restart: no
    env_file:
      - 'env-db-write.env'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $POSTGRES_DB_WRITE" ]
    volumes:
      - crm-postgres-write:/var/lib/postgresql/data
    network_mode: host

  burdok:
    container_name: burdok
    image: burdok:latest
    restart: no
    env_file:
      - 'env-burdok.env'
    depends_on:
      crm-postgres-write:
        condition: service_healthy
    volumes:
      - burdok-doc:/documents
    network_mode: host

volumes:
  crm-postgres-write:
    name: crm-postgres-write
  burdok-doc:
    name: burdok-doc