package pl.bodzioch.damian.document;

public enum DocumentType {
    REPORT,
    CONSENT,
    COACH_INVOICE,
    PROVIDER_INVOICE,
    INTERMEDIARY_INVOICE,
    PARTICIPANT_BUR_QUESTIONNAIRE,
    CUSTOMER_BUR_QUESTIONNAIRE,
    PARTICIPANT_PROVIDER_QUESTIONNAIRE,
    ATTENDANCE_LIST,
    PRESENTATION
}
