INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'DOLNOŚLĄSKA AGENCJA ROZWOJU REGIONALNEGO SPÓŁKA AKCYJNA', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Łódzka Agencja Rozwoju Regionalnego S.A.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'MAŁOPOLSKA AGENCJA ROZWOJU REGIONALNEGO S.A.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Fundacja Rozwoju Regionu Rabka', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Stowarzyszenie na Rzecz Szkoły Zarządzania i Handlu w Oświęcimiu', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Miasto Nowy Sącz-Centrum Pozyskiwania Funduszy i Przedsiębiorczości', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'KDK Info spółka z ograniczoną odpowiedzialnością', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Agencja Rozwoju Regionalnego MARR S.A.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'ŁÓDZKA IZBA PRZEMYSŁOWO-HANDLOWA', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Instytut ADN spółka z ograniczoną odpowiedzialnością sp.k.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'HRP GRANTS Sp. z o. o.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Rzeszowska Agencja Rozwoju Regionalnego S.A.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Wojewódzki Urząd Pracy w Kielcach', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Krajowa Agencja Informacyjna INFO Spółka z ograniczoną odpowiedzialnością', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Techpal Sp. z o.o.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'Wielkopolska Agencja Rozwoju Przedsiębiorczoś ci Sp. z o.o.', 1);
INSERT INTO operator(opr_uuid, opr_name, opr_created_by) VALUES (gen_random_uuid(), 'KRAJOWA IZBA GOSPODARCZA', 1);
