INSERT INTO public.users (usr_uuid,
                          usr_version,
                          usr_password,
                          usr_email,
                          usr_first_name,
                          usr_last_name,
                          usr_roles,
                          usr_last_login,
                          usr_created_at,
                          usr_modified_at,
                          usr_created_by,
                          usr_modified_by)
VALUES ('018f20c6-f751-7cd0-9a21-d664f785ddb3',
        0,
        '$2a$10$hFP0QUed/sCyAcBG0xQ2kO5z95l1xVQPQsB.Qq3ADO.NcZFtihygW',
        'szaddaj@gmail.com',
        'Damian',
        'Bodzioch',
        'USER;MANAGER;ADMIN',
        null,
        '2024-04-27 20:17:41.456886',
        null,
        1,
        null);